runtime: python37

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /css/(.*)
    static_files: css/\1
    upload: css/(.*)

  - url: /scripts/(.*)
    static_files: scripts/\1
    upload: scripts/(.*)
